---
# PostgreSQL Storage Configuration

postgresql_version: "18"

postgresql_user: "postgres"
postgresql_group: "postgres"

postgresql_data_dir: "/pgdata"
postgresql_wal_dir: "/pgwal"
postgresql_wal_link: "{{ postgresql_data_dir }}/pg_wal"

postgresql_data_dir_mode: "0700"
postgresql_wal_dir_mode: "0700"
