[primary]
dblab01 ansible_host=127.0.0.1 ansible_port=2222 ansible_ssh_private_key_file=/Users/phanipinjala/VMs/.vagrant/machines/dblab01/vmware_desktop/private_key

[standby]
dblab02 ansible_host=127.0.0.1 ansible_port=2200 ansible_ssh_private_key_file=/Users/phanipinjala/VMs/.vagrant/machines/dblab02/vmware_desktop/private_key
dblab03 ansible_host=127.0.0.1 ansible_port=2201 ansible_ssh_private_key_file=/Users/phanipinjala/VMs/.vagrant/machines/dblab03/vmware_desktop/private_key

[postgresql:children]
primary
standby

[postgresql:vars]
ansible_user=vagrant
ansible_become=true
ansible_become_method=sudo
