---
- name: Configure PostgreSQL repository
  ansible.builtin.import_tasks: repository.yml

- name: Install PostgreSQL packages
  ansible.builtin.import_tasks: packages.yml

- name: Verify PostgreSQL installation
  ansible.builtin.import_tasks: verify.yml
